IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TESTE_IAGO' AND TABLE_NAME = 'PESSOA') 
	BEGIN
		CREATE TABLE TESTE_IAGO.PESSOA (
			ID int IDENTITY(1,1) NOT NULL,
			NOME varchar(250) COLLATE Latin1_General_CI_AS NOT NULL,
			CPF varchar(11) COLLATE Latin1_General_CI_AS NULL,
			DATA_NASCIMENTO date NOT NULL,
			EMAIL varchar(100) COLLATE Latin1_General_CI_AS NOT NULL
			PRIMARY KEY CLUSTERED 
		(
			ID ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
		)

	END