IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TESTE_IAGO' AND TABLE_NAME = 'TELEFONE') 
	BEGIN
		CREATE TABLE TESTE_IAGO.TELEFONE (
			ID int IDENTITY(1,1) NOT NULL,
			DDD varchar(3) NOT NULL,
			NUMERO int NOT NULL,
			PESSOA_FK int NOT NULL,
			PRIMARY KEY CLUSTERED 
		(
			ID ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
		)

		ALTER TABLE [TESTE_IAGO].[TELEFONE]  WITH CHECK ADD  CONSTRAINT [CNT_TELEFONE_PESSOA_FK] FOREIGN KEY([PESSOA_FK])
		REFERENCES [TESTE_IAGO].[PESSOA] ([ID])

		ALTER TABLE [TESTE_IAGO].[TELEFONE] CHECK CONSTRAINT [CNT_TELEFONE_PESSOA_FK]
		
	END